### PR TITLE
Clarify difference between durations and periods

### PR DESCRIPTION
**Pull request by vikeri**

### CODE REVIEW

**Comment by henryw374** [comment]
I'm not sure this is the best explanation. Reading 'when the units range from nanoseconds to days' I might think any span of time shorter than a day should be modelled by a Duration. Also it sounds like days is a unit of Duration, which it isn't

The javadoc explains it in terms time-based (hours, mins and smaller) vs date-based (years,months & days only). If I had to explain why there are two I'd say all the date-based units are variable length (leap years, DST etc) and the time based ones are not. So for example a `Duration` of 48 hours is not always the same span as a `Period` of 2 days

**Comment by vikeri** [comment]
Yes that is definitely a clearer explanation. Duration does accept `:days` as a unit though, even though it gets translated into hours.

**Comment by henryw374** [comment]
Ah, I didn't realise there was a `:days` constructor.

**Comment by henryw374** [comment]
I've changed the docs again, https://github.com/juxt/tick/commit/d0f5b8eb5ae8a5d6b7276a7552f47777b984cb69 . I'd be happy to hear any further suggestions

**Pull request merged**
